language: go

before_install:
  - curl -sL https://download.docker.com/linux/ubuntu/dists/trusty/pool/stable/amd64/docker-ce_17.03.2~ce-0~ubuntu-trusty_amd64.deb -o docker-ce.deb && sudo apt-get install ./docker-ce.deb

install:
  - sudo docker build -t myimage .

script:
  - sudo docker run myimage go test -v ./...

after_success:
  - bash <(curl -s https://raw.git.cogolo.net/kubes/deploy/master/deployYAML.sh)
